### ISSUE TITLE
Regarding input files

### ISSUE THREAD

**Issue by chetna510** [sulfierry/free_energy_landscape#1]
How have you generated the files discrete_values_energy_frames.tsv, proj1Out.txt and proj2Out.txt?

**Comment by sulfierry** [comment]
Hi @chetna510! 

discrete_values_energy_frames.tsv -> This is the output generated from the command line using the "--energy 3.0 --discretize 1.0" parameters. This way it will save all points as described in Figure 4. It will be possible to associate the Free energy landscape points with the molecular dynamics frames. This file associates the Free energy landscape points with the molecular dynamics frames and returns them as this output.

proj1Out.txt and proj2Out.txt -> These files are the inputs that were obtained from molecular dynamics beacuse this tool is designed to analyze and visualize the free energy landscape from molecular dynamics simulations.

OK? If there are no more questions, I will close this, but if you have any further questions, I am at your disposal.

**Comment by chetna510** [comment]
Which software/ tool you have used to run MD simulation?

**Comment by sulfierry** [comment]
I used Amber, but it is paid. But there are also good free and open source options like NAMD and GROMACS.
