### ISSUE TITLE
how to extract minima PDB 

### ISSUE THREAD

**Issue by MuthusaravananS** [sulfierry/free_energy_landscape#2]
how to extract minima time frame or PDB

**Comment by sulfierry** [comment]
Hi @MuthusaravananS, just use the "--energy" parameter in your execution line. 

For example:

--energy 3.0: will search for all points with energy less than or equal to 3KJ/mol.

Then you will receive an output "discrete_values_energy_frames.tsv" containing all the energy values ​​for each frame. Once you know which frame is related to the respective energy value, simply remove the respective frame from your trajectory.

If you want to view different points according to energy, just use the " --discretize" parameter. For example,  
--discretize 1.0: will discretize the image points every 1 KJ/mol.

**Comment by sulfierry** [comment]
I will close this issue. If you have any further questions, I will be available to help.
